-- CECI EST UN COMMENTAIRE
-- REQUETE DE STRUCTURE
-- CREATION D'UNE BDD AVEC CREATE DATABASE
CREATE DATABASE test;

-- DIRE LA BDD QU'ON SOUHAITE UTILISER
USE test;

-- CREATION D'UNE TABLE AU SEIN DE MA BDD TEST AVEC CREATE TABLE
CREATE TABLE users (
	id_user INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    login VARCHAR(50) NOT NULL UNIQUE,
    name_user VARCHAR(50),
    mdp_user VARCHAR(150) NOT NULL
)ENGINE = innoDB;


-- CREATION D'UNE TABLE ARTICLES OU RIEN NE VA !
CREATE TABLE articles(
	id_articles INT,
    titre VARCHAR(255),
    content TEXT
)ENGINE = innoDB;

-- MODIFIER LA STRUCTURE D'UNE TABLE --> ALTER TABLE
-- AJOUTER UNE CLE PRIMAIRE
ALTER TABLE articles ADD PRIMARY KEY (id_articles);

-- MODIFIER LES PROPRIETE D'UNE COLONNE
ALTER TABLE articles MODIFY COLUMN id_articles INT AUTO_INCREMENT NOT NULL;

-- MODIFIER LE NOM D'UNE COLONNE
ALTER TABLE articles CHANGE titre title VARCHAR(255);

-- AJOUTER UNE COLONNE
ALTER TABLE articles ADD COLUMN id_user INT;

-- AJOUTER UNE CLE ETRANGERE
ALTER TABLE articles ADD CONSTRAINT FOREIGN KEY (id_user) REFERENCES users(id_user);

-- SUPPRESSION D'UNE COLONNE 
ALTER TABLE articles DROP content;

-- SUPPRESSION D'UNE CONTRAINTE
ALTER TABLE articles DROP CONSTRAINT articles_ibfk_1;

-- AJOUTER UNE CLE ETRANGERE EN LUI CHOISSISSANT UN NOM
ALTER TABLE articles ADD CONSTRAINT ma_cle_article_user FOREIGN KEY (id_user) REFERENCES users(id_user);

-- RENOMMER UNE TABLE 
-- RENAME TABLE ancien_nom TO nouveau_nom;